DjangoWebProject2/DjangoWebProject2/urls.py
"""
Definition of urls for DjangoWebProject2.
"""

from datetime import datetime
from django.conf.urls import patterns, url, include
from app.forms import BootstrapAuthenticationForm
from django.contrib import admin
from app.views import *
from PIL import Image
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.contrib.auth.decorators import login_required
# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', Home.as_view(), name='home'),
    url(r'^contact$', 'app.views.contact', name='contact'),
    #url(r'^error404', error404.as_view(), name='404'),
    url(r'^about', 'app.views.about', name='about'),
    #url(r'^login', VistaSignUp.as_view(), name='login'),
    url(r'^registro', VistaSignUp.as_view(), name='signup'),
    url(r'^perfilArtistaNp/(?P<userid>\w{1,50})$', perfilArtistaNp.as_view(), name='perfilArtistaNp'),
    url(r'^perfilArtista', perfilArtista.as_view(), name='perfilArtista'),
    url(r'^perfilNormalNp/(?P<normalid>\w{1,50})$', perfilNormalNp.as_view(), name='perfilNormalNp'),
    url(r'^perfilNormal', perfilNormal.as_view(), name='perfilNormal'),
    url(r'^perfilBandaNp/(?P<bandaid>\w{1,50})$', perfilBandaNp.as_view(), name='perfilBandaNp'),
    url(r'^noImplementado/(?P<template>\w{1,50})$', NoImplementado.as_view(), name='noImplementado'),
    url(r'^perfilBanda/(?P<bandaid>\w{1,50})$', perfilBanda.as_view(), name='perfilBanda'),
    url(r'^infoDisco/(?P<dId>\w{1,50})$', infoDisco.as_view(), name='infoDisco'),
    url(r'^infoDiscoE/(?P<dId>\w{1,50})$', infoDiscoE.as_view(), name='infoDiscoE'),
    url(r'^addDisco/(?P<bId>\w{1,50})$', addDisco.as_view(), name='addDisco'),
    url(r'^crearBanda', crearBanda.as_view(), name='crearBanda'),
    url(r'^config', config.as_view(), name='config'),
    url(r'^busqueda$', busqueda.as_view(), name='busqueda'),
    url(r'^guardarDatosArtista$', guardarDatosArtista, name='updatePA'),
    url(r'^guardarDatosBanda$', guardarDatosBanda, name='updateB'),
    url(r'^guardarDatosNormal$', guardarDatosNormal, name='updatePN'),
    url(r'^guardarDatosPersonales$', guardarDatosPersonales, name='updateP'), 
    url(r'^agregarMaterial$', agregarMaterial, name='addM'),   
    url(r'^crearDisco$', crearDisco, name='addD'),
    url(r'^crearCancion$', crearCancion, name='addC'),
    url(r'^upload$', upload_file, name='upload'),
    url(r'^search', search),#buscador
    url(r'^universalsearch', universalsearch),#buscador
    url(r'^autoPoblado', poblacionBd),
    url(r'^login/$',
        'django.contrib.auth.views.login',
        {
            'template_name': 'app/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title':'Log in',
                'year':datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        'django.contrib.auth.views.logout',
        {
            'next_page': '/login/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^(?P<loquesea>\w{1,300})$', error404.as_view(), name='error'),
    
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoWebProject2/app/forms.py
# -*- coding: utf-8 -*-
"""
Definition of forms.
"""
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from datetime import datetime
from django.forms import ModelForm
from models import *
from datetime import datetime, timedelta, date



class CrearBandaForm(forms.Form):
    nombre = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control validate'}))
    choice_g = sorted([ (gen.nombre,gen.nombre) for gen in Genero.objects.all()])
    choice_y = [(str(year), year) for year in range(1900, 2016) ]
    choice_y.reverse()
    meses = ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septembrie", "Octubre", "Noviembre", "Diciembre"]
    choice_m = []
    for i in range(0,12):
        choice_m.append((i+1, meses[i]))
        
    
    genero = forms.ChoiceField(choices = choice_g, widget=forms.Select({
                                   'class': 'browser-default'}))
    mes = forms.ChoiceField(choices = choice_m, widget=forms.Select({
                                   'class': 'browser-default'}))
    year = forms.ChoiceField(choices = choice_y, widget=forms.Select({
                                   'class': 'browser-default'}))
    
class RegistroForm(forms.Form):
    name = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control validate'}))
    password1 = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'id':'contras',
                                   'class': 'form-control validate'}))
    password2 = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'id':'contras2',
                                   'class': 'form-control validate'}))
    email = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'type':'email',
                                   'class': 'form-control validate'}))
    tipo = forms.BooleanField(widget=forms.CheckboxInput(), required=False)
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if not password2:
            raise forms.ValidationError("Debe confirmar su contraseña")
        if password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return password2
class LoginForm(forms.Form):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'type':'email',
                                   'class': 'form-control validate'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'id':'contras',
                                   'class': 'form-control validate'}))
        
class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'type':'email',
                                   'class': 'form-control validate'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'id':'contras',
                                   'class': 'form-control validate'}))
                                   
#class UploadFileForm(forms.Form):
#    file_ = forms.FileField(widget = focrms.ClearableFileInput({'class':'file-path validate'}))

DjangoWebProject2/app/templates/app/EventosUN.html
{% extends "app/layout.html" %}

{% block sidebar %}
    {% if tipoUsuario == 1  %}
        {% include "app/sidebarartistapartial.html" %}
    {% elif tipoUsuario == 2 %}
        {% include "app/sidebarnormalpartial.html" %}
    {% endif%}
{% endblock %}

{% block content %}
<div class="container" style="width:100%;padding:0;">
    <div class="row" style="    margin-left: 0;margin-right: 0;">
    {% for i in "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" %}
      <div class="col l4 m6 s12"> 
        <div class="card color-principal">
            <div class="card-image ">
              <div style="height:0px;margin-bottom:70%">
                {% load staticfiles %}
                 <img class="activator" src="{% static 'app/images/evento_rock.jpg' %}" >
              </div>
                  <span class="card-title activator " style="text-shadow:0px 0px 3px #000; margin-bottom:-70%"><b>Evento2</b></span>
                </div>
                <div class="card-reveal">
                  <span class="card-title grey-text text-darken-4">Evento<i class="material-icons right">close</i></span>
                  <p>Evento de rock{# aqui el rishar tiene que ponerle el estilo#}</p>
                  <p><a href="#">Ver pagina del evento</a></p>
                </div>
              </div>
        </div>
    {% endfor %}
    </div>
    <div class="filter-bar hide-on-small-only" >
    
    <div class="container">
        <div class="row">
        <ul class="grey-text text-darken-3">
            <li class="valign-wrapper" ><h5>Filtros</h5></li>
            <li class="divider grey"></li>

            <li>
              <input placeholder="Fecha" type="date" class="datepicker">
            </li>
            <li >
              <label for="test5">Rango de fecha [1-15]</label>
              <p class="range-field">
              <input type="range" id="test5" min="1" max="15" value="1" />
              <style type="text/css"></style>
              </p>
            </li>
            <li>
              <input name="opt" type="radio" id="filled-in-box"/>
              <label for="filled-in-box">Opcion 1</label>
              &nbsp;
              <input name="opt" type="radio" id="filled-in-box2"/>
              <label for="filled-in-box2">Opcion 2</label>
            </li>
            <li>
              <div class="input-field col s12">
                <select>
                  <option value="" disabled selected>Selecciona Genero</option>
                  <option value="1">Genero 1</option>
                  <option value="2">Genero 2</option>
                  <option value="3">Genero 3</option>
                </select>
              </div>
            </li>
            <li><h5 class="btn" style="width:100%"><i class="material-icons">youtube_searched_for</i></h5></li>
        </ul>
        </div>
    </div>
</div>
</div>
{% endblock %}

{% block scripts %}
{% load staticfiles %}
	<script src="{% static 'app/scripts/materialize.min.js' %}"></script>

{% endblock %}

DjangoWebProject2/app/templates/app/crearBanda.html
{% extends "app/layout.html" %}

{% block sidebar %}
    {% if tipoUsuario == 1  %}
        {% include "app/sidebarartistapartial.html" %}
    {% endif%}

{% endblock %}

{% block content %}
<div class="container">
    <form action="/crearBanda" id="crearBanda" method="POST" class="form-horizontal">
            {% csrf_token %}
    <div class="row">
        <div class="col s12"> 
            
            <h5>Creando una banda</h5>
            <div class="input-field col s12">
              {{ form.nombre }}
              <label for="id_nombre">Nombre Banda</label>
                
              
            </div>
    
                <div class="row">
                    <div class="col s12">
                        <div class="input-field col s6">
                            <label>Genero</label>
                            <br><br>
                           {{ form.genero }} 
                        </div>

                        <div class="input-field col s4">
                            <label>Fundada en:</label>
                            <br><br>
                            {{ form.mes }} 
                            
                        </div>

                        <div class="input-field col s2">
                            <label></label>
                            <br><br>
                            {{ form.year }} 
                            
                        </div>  
                    </div>
                </div>
                <div class="col s12">
                        <button class="btn waves-effect waves-light" id="cerrarMCB">Cerrar</button>
                        <button class="btn waves-effect waves-light" type="submit" name="action">Crear Banda</button>
                </div>
    </div>
    </form>
</div>  
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-error">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-error">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

{% load staticfiles %}



{% endblock %}

DjangoWebProject2/app/templates/app/disco.html
<h5 class="white-text">{{disco.banda}}</h5>
<h5 class="white-text" style="margin-left:20px">{{disco.nombre|title}} <span class="grey-text " style="font-size:15px">{{disco.lanzamiento.year}}</span></h5>
<ul class="collection">
{%for c in canciones%}
	<li class="collection-item ">
		<div class="valign-wrapper left" style="margin-right:20px;" ><i class="material-icons blue darken-3 white-text" style="padding:8px;">&#xE405;</i></div>
		{{c.nombre|title}}<br><span class="stext grey-text">{{c.autor}}</span>
		<span class="secondary-content">{{c.duracion}}</span>
	</li>
{%endfor%}
{%if canciones|length < 1 %}
	<li class="collection-item grey lighten-2 grey-text text-darken-2">
		<div class="valign-wrapper left" style="margin-right:20px;" ><i class="material-icons grey darken-3 white-text" style="padding:8px;">info</i></div>
		Este disco aún no tiene canciones<br><span class="stext grey-text">La banda</span>
		<span class="secondary-content">-</span>
	</li>
{%endif%}
</ul>

DjangoWebProject2/app/templates/app/discoE.html
<h5 class="white-text">{{disco.banda}}</h5>
<h5 class="white-text" style="margin-left:20px">{{disco.nombre|title}} <span class="grey-text " style="font-size:15px">{{disco.lanzamiento.year}}</span></h5>
<ul class="collection"  >
{%for c in canciones%}
	<li class="collection-item ">
		
		<div class="valign-wrapper left" style="margin-right:20px;" ><i class="material-icons blue darken-3 white-text" style="padding:8px;">&#xE405;</i></div>
		{{c.nombre|title}}<br><span class="stext grey-text">{{c.autor}}</span>
		<span class="right white red-text text-darken-2 valign-wrapper" style="height:10px" onclick="removeCancion({{c.id}})"><i class="material-icons">remove_circle</i></span>
		<span class="secondary-content">{{c.duracion}}</span>
	</li>
{%endfor%}
	<li class="collection-item grey lighten-4 grey-text hover-grey no-select manito text-darken-2 addTrigger">
		<div class="valign-wrapper left" style="margin-right:20px;" ><i class="material-icons grey darken-3 white-text" style="padding:8px;">&#xE147;</i></div>
		Añadir Canción<br><span class="stext grey-text"> &nbsp; </span>
	</li>
	<li class="collection-item green darken-1 white-text center-align no-select manito text-darken-2 hide tougle" onclick="disco_send();">
		<h5>Añadir Canción</h5>	
	</li>
</ul>
<script type="text/javascript">
var counter=0;
$('.addTrigger').click(function(){
	$(this).before(songGen());
	$('.hide.tougle').removeClass('hide');
});
function songGen(){
	var t1 = '<li class="collection-item song grey lighten-4 grey-text text-darken-2">'+
	'<div class="valign-wrapper left" style="margin-right:20px;" ><i class="material-icons blue darken-3 white-text" style="padding:8px;">&#xE405;</i></div>'+
    '<div class="input-field col s6 w60p inline" style="margin-top:10px">'+
	'<input id="nameSong'+(++counter)+'" name="nombre" type="text" class="validate">'+
	'<label for="nameSong'+(++counter)+'">Nombre de Canción</label>'+
	'</div>'+
	'<br>'+
	'<div class="input-field col s6 w60p inline" style="margin-top:10px;">'+
	'<input id="nameSong'+(++counter)+'" name="autor" type="text" class="validate" style="font-size:12px;height:2.5em;">'+
	'<label for="nameSong'+(++counter)+'">Autor</label>'+
	'</div>'+
	'<div class="input-field secondary-content col s6 inline" style="margin-top:10px; width:80px;">'+
	'<input id="duracion'+(++counter)+'" type="time" name="duracion" class="validate" value="00:00" style="font-size:12px;height:2.5em;">'+
	'<label for="duracion'+(++counter)+'" style="transform:translateY(-140%);font-size: 0.8rem;">Duración</label>'+
	'</div>'+
	'</li>';
	return t1;
}
function disco_send(){
	var cancionN = $('.song input[name=nombre]');
	var cancionA = $('.song input[name=autor]');
	var cancionD = $('.song input[name=duracion]');
	var canciones='[';
	cancionN.each(function (k,v){
		canciones += '{"nombre":"'+$(v).val()+'","autor":"'+$(cancionA[k]).val()+'","duracion":"'+$(cancionD[k]).val()+'"},';
	});
	 canciones = canciones.substring(0, canciones.length-1)+']';
	console.log(canciones);
	$.ajax({
		url : "/crearCancion", // the endpoint
		type : "POST", // http method
		
		data : {bid : $('.container.sfull').attr('id-banda'),
				did : '{{disco.id}}',
				'cancion':canciones, }, // data sent with the post request
		// handle a successful response
		success : function(response) {
			console.log(response); // log the returned json to the console
			var id = response.split(',');
			if(id[0]=="k"){
				Materialize.toast('<span class="green-text"><i class="material-icons">&#xE5CA;</i></span>Canci&oacute;n agregada', 4000);
				
				//$('.no-hay-material').remove();
				$('#modalDisco').closeModal();
			}
			else
				respuestaInstatisfactoria(response);
		},
		// handle a non-successful response
		error : function(xhr,errmsg,err) {
			console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
		}
	});
}
function removeCancion(cId,confirmado){
	if(confirmado){
		
		$('.rem-confirm').remove();
		bid= $('.container.sfull').attr('id-banda');
		$.ajax({
			url: "/guardarDatosBanda",
			type: 'POST',
			data: {
				bid:bid,
				target:'cancion-delete',
				dato:cId,
			},
			success: function (data) {
				var id = data.split(',');
				if(id[0]=="k"){
					Materialize.toast('<span class="green-text"><i class="material-icons">&#xE5CA;</i></span>'+id[1], 4000);
					$('#modalDisco').closeModal();		
				}else
					respuestaInstatisfactoria(data);
			},
			error: function (data) {
				Materialize.toast('<span class="red-text"><i class="material-icons">&#xE14C;</i></span>Error al quitar el material', 4000);
			},
		});
	}else{
		Materialize.toast('<span class="yellow-text"><i class="material-icons">&#xE002;</i></span>¿Estás seguro que deseas quitar el material?<a style="margin-left:10px;" href="#" onclick="removeCancion('+cId+',true);"><b>SI</b></a>', 10000,"rem-confirm");
	}
}
</script>

DjangoWebProject2/app/templates/app/evento.html
{% extends "app/layout.html" %}

{% block sidebar %}
    {% if tipoUsuario == 1  %}
        {% include "app/sidebarartistapartial.html" %}
    {% elif tipoUsuario == 2 %}
        {% include "app/sidebarnormalpartial.html" %}
    {% endif%}
{% endblock %}

{% block content %}

<div class="container">
        <div class="row">
            <br><br>
            <h4>CREANDO EVENTO</h4> 
            <div class="input-field col s8">
                <input id="last_name" type="text" class="validate">
                <label for="last_name">> Nombre del evento <</label>         
            </div>
            <div class="input-field col s1">
                <input id="last_name" type="text" class="validate">
                <label for="last_name">DD</label>
            </div>
            <div class="input-field col s1">
                <input id="last_name" type="text" class="validate">
                <label for="last_name">HH</label>
            </div>
            <div class="input-field col s1">
                <input id="last_name" type="text" class="validate">
                <label for="last_name">MM</label>
            </div>
            <div class="input-field col s1">
                <input id="last_name" type="text" class="validate">
                <label for="last_name">SS</label>
            </div>
        </div>

        <div class="row">
            <form class="col s12">
                <div class="row">
                    <div class="input-field col s12">
                        <textarea id="textarea1" class="materialize-textarea"></textarea>
                        <label for="textarea1">Información</label>
                    </div>
                </div>
            </form>
        </div>

        <div>
            <h6 class="right-align">Fecha - Hora - Lugar</h6>
        </div>


        <div class="row">               
            <div class="input-field col s12">
                <div class="input-field col s6">
                    <h5>Bandas participantes</h5>
                    <ul class="collection">
                          <a href="#!"  class="collection-item avatar">
                          <div class="circle avatar-img dropdown-button"><img src="/media/app/static/app/images/guitarra.jpg" alt="" style="height:50px;"></div>
                          <span class="title left-align"><br>Los zolezzi</span>
                        </a>

                        <a href="#!"  class="collection-item avatar">
                          <div class="circle avatar-img dropdown-button"><img src="/media/app/static/app/images/guitarra.jpg" alt="" style="height:50px;"></div>
                          <span class="title left-align"><br>Elefantes Felices</span>
                        </a>

                        <a href="#!"  class="collection-item avatar">
                          <div class="circle avatar-img dropdown-button"><img src="/media/app/static/app/images/guitarra.jpg" alt="" style="height:50px;"></div>
                          <span class="title left-align"><br>Terminator 3</span>
                        </a>
                    </ul>
                </div>  
                <!-- http://embedgooglemaps.com/?page_id=77&lang=es  es para generar este codigo-->
                 <div class="input-field col s6">
                       <iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0"width="470" height="400" src="https://maps.google.com/maps?hl=en&q=Universidad de Santiago de Chile Av. Libertador Bernardo O`Higgins 3363 Santiago Región Metropolitana&ie=UTF8&t=m&z=15&iwloc=B&output=embed"><div><small><a href="http://www.embedgooglemaps.com/?page_id=77&lang=es">embedgooglemaps.com</a></small></div><div><small><a href="http://www.embedgooglemaps.com/?page_id=77&lang=es">Generere e inserte Google Maps aqui</a></small></div></iframe>
                </div>  

            </div>
        </div>






    </div>


{% endblock %}
{% block scripts %}


{% endblock %}

DjangoWebProject2/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - uMusic</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/materialize.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
</head>

<body class="grey lighten-2">
    
    <nav class="navbar" style="position:fixed;top:0;" >
       	<div class="color-333 nav-wrapper">
            <div class="col left w200px"> 
                <a class="b-logo" href="/">
                    <img alt="Brand" class="logo-img" src="{% static 'app/images/logo.png' %}">
                </a>
            </div>
           
                     
            <div class="container right" style="width: calc(100% - 220px);height: 80px;"> 
                <div class="col dropdown-button right grey-text text-lighten-2 valign-wrapper" data-beloworigin="true" data-activates='dropdown1'  style="max-width:100%;cursor:pointer; ">
                    <div id="nombre-navbar" class="truncate" >{{ user.first_name|title }}</div>
                    <div class="circle avatar-img myavatar dropdown-button"  data-beloworigin="true" data-activates='dropdown1'><img src="{{user.profile.imagenPerfil.url}}" alt="" style="height:50px;"></div>
                </div>
               <div class="col s12 l9  campo-editable">
                    <div class="input-field hide-on-small-only valign-wrapper" >
                        <input type="search" name="universalsearch" id="search-field" class="field valign"  required maxlength="">
                        <label for="search-field" style="padding-top: 8px;"><i class="mdi-action-search"></i></label>
                    </div>

                    <div class="collection result-list-u" style="max-height:500px;cursor:pointer;overflow-y:scroll;position: absolute;margin:0;margin-top:-15px;border:solid 1px #ccc">
                    </div>
                </div>
                <ul id='dropdown1'  class='grey darken-3 dropdown-content' style="min-width:200px;" data-beloworigin="true">
                    <li><a href="#!" class="button-collapse hide-on-med-and-up" data-activates="mobile-demo"><i class="material-icons">menu</i> Sidebar</a></li>
                    <li><a href="{% url 'config' %}">Configuraciones</a></li>
                    <li class="divider"></li>
                    <li>
                        <a href="javascript:document.getElementById('logoutForm').submit()">Cerrar Sesion</a>
                    </li>
                </ul>
                    <form id="logoutForm" action="/logout" method="post" class="navbar-right">
                     {% csrf_token %}
                    </form>
               

                </div>

            </div>

        </nav>

{% block sidebar %}{% endblock %}
    <div class="body-content " >
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - Fingeso Grupo 3 </p>
            <p></p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.min.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/materialize.min.js' %}"></script>
    <script src="{% static 'app/scripts/artistasearch.js' %}"></script>
    <script type="text/javascript">
        $('.dropdown-button').dropdown({
            inDuration: 300,
            outDuration: 225,
            constrain_width: true, // Does not change width of dropdown to that of the activator
            hover: false, // Activate on hover
            belowOrigin: true // Displays dropdown below the button
        });
        $(".button-collapse").sideNav();
        
    </script>

{% block scripts %}{% endblock %}

</body>
</html>

DjangoWebProject2/app/templates/app/login.html
{% extends "app/login-layout.html" %}
{% block tabs %}
    <div class="col s6" style="color:#00bcd4; border-bottom:4px solid #00bcd4 !important; ">Iniciar Sesión</div>
    <a style="color:#00bcd4;" href="/registro"><div class="col s6 hover-underline">Registrarse</div></a>
    
{% endblock %}
{% block formulario %}

<div id="login" class="col s12" style="margin-top:30px">
    <form action="." method="post" class="form-horizontal">
    {% csrf_token %}
        <div class="form-group">
            <div class="col s12 input-field">
                {{ form.username }}
                <label for="id_username" class="active">Correo</label>
            </div>
        </div>
    {# Para editar el hint de los inputs, ir a forms.py en el cuerpo de la funcion estan los parametros#}
    <div class="form-group">
        <div class="input-field col s12">
            {{ form.password }}
            <label class="active" for="contras">Contraseña</label>
        </div>
    </div>
    <div class="form-group">
        <div class="col s12">
            <input type="hidden" name="next" value="/" />
            <input type="submit" value="Ingresar" class="btn btn-default color-principal" />
        </div>
    </div>
    {% if form.errors %}
    <p class="validation-summary-errors col s12">Los datos ingresados son incorrectos.</p>
    {% endif %}
    </form>
</div>
{% endblock %}

DjangoWebProject2/app/templates/app/usuarioCreado.html
{% extends "app/layout.html" %}

{% block content %}

<details>
    <summary>Usuario creado correctamente</summary>
    <table>
      <tr>
        <th scope="row">Nombre</th>
        <td>{{nombre}}</td>
      </tr>
      <tr>
        <th scope="row">Correo</th>
        <td>{{email}}</td>
      </tr>
       <tr>
        <th scope="row">Creado</th>
        <td>{{creado}}</td>
      </tr> 
	</table>
</details>
{% endblock %}